# Generated by Django 5.1 on 2024-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=0.0, max_length=10),
        ),
    ]
